### ISSUE TITLE
Frontend Technical interview

### ISSUE THREAD

**Issue by meiti-x** [alibaba-aero/technical-interview#10]
سلام  امکانش هست سوال های فرانت هم قرار بدید ؟

**Comment by MDP66** [comment]
مهدی جان، بسمالله،
خودت یه درفتی بزن، بچه های فرانت تکمیلش می کنن.

**Comment by meiti-x** [comment]
> مهدی جان، بسمالله، خودت یه درفتی بزن، بچه های فرانت تکمیلش می کنن.


سلام اوکیه. 
فقط روالش چجوری باشه بر اساس سطح دسته بندی بشه(مثلا جونیور) یا بر اساس موضوع مثلا react

**Comment by amiru3f** [comment]
Hey dear friend 🥰,
Please let us double check with our front chapter, We will let you know ASAP.

Thanks for your notice.

**Comment by meiti-x** [comment]
Hey dear friend :kissing: ,
Okay, I'm waiting for your double check :)

**Comment by meiti-x** [comment]
بعد از گذشت ۳ ماه هنوز هیچ خبری نیست !!!
تیم شما یه درفت نصفه نیمه(هر چند ناقص مهم نیست) بسازد تا بقیه تکمیل کنند. ناسلامتی پروژه اوپن سورس هستشا.

اگر هم  کلا پلنی برای ساخت ندارید  این ایشیو رو کلوز کنید. ممنون

**Comment by mHooshdar** [comment]
> بعد از گذشت ۳ ماه هنوز هیچ خبری نیست !!! تیم شما یه درفت نصفه نیمه(هر چند ناقص مهم نیست) بسازد تا بقیه تکمیل کنند. ناسلامتی پروژه اوپن سورس هستشا.
> 
> اگر هم کلا پلنی برای ساخت ندارید این ایشیو رو کلوز کنید. ممنون

Check this PR: #18 

It's a draft markdown for frontend interview questions. Thanks in advance for contributing
